name: Github Action Demo
on: 
  push:
    branches:  #Now we need to specify the branch name
    - main   
jobs: 
  lint:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          docker build -t flask-app .
          docker run -d -p 5001:5000 flask-app
      
        
      