name: Github Action Demo
on: 
  push:
    branches:  #Now we need to specify the branch name
    - main   
jobs: 
  lint:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.9
        uses: actions/setup-python@v4
        with:
            python-version: 3.12.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          kill $(pgrep -f flask)
          RUNNER_TRACKING_ID="" && (nohup flask --app hello run > log.txt 2>&1 &)
    #   - name: Run linter
    #     run: |
    #       pip install flake8
    #       flake8 .
    #   - name: Run tests
    #     run: |
    #       pip install pytest
    #       pytest tests/
        
      